Parallel Retrieve Cursor Implementation v2
This a squash commit for all the changes after the first PR review.
The squashed history can be found on branch:
https://github.com/liming01/gpdb/tree/feature_parallelcursor_bk190930

Interface Changes:
- To avoid conflicts with PG, term parallel cursor has been renamed to
  parallel retrieve cursor.
- EXECUTE statement is not needed anymore. Once the cursor is declared,
  the endpoints are ready to be retrieved.
- To check the endpoint status on master, two UDF are supplied in
  blocking and non-blocking mode.
- Endpoint name is added as the identification for endpoint instead of
  token. Token is only used for authentication now.

Check the README for more details.

Implementation Changes:
- DECLARE statement will ensure the endpoints are ready when it returns.
- Instead of using CreateTableAs, the impl is following normal cursor
  execution logic.
- The query plan is like below:
  - When endpoint is on segment, the master node should have no query
    slice to run. It just dispatches the query to the QE, and monitors
    their execution states.
  - When endpoint is on master, the root query slice is dispatched to
    entrydb for execution.
- Token authentication behaviour changes. Retrieve session will be
  limited to retrieve only from the endpoints with the same token.

Co-Authored-By: Chen Mulong <chenmulong@gmail.com>
Co-Authored-By: (Jerome)Junfeng Yang <jeyang@pivotal.io>
Co-Authored-By: Ming LI <mli@apache.org>
Co-Authored-By: Wen Lin <wlin@pivotal.io>

diff --git a/src/test/isolation2/Makefile b/src/test/isolation2/Makefile
--- a/src/test/isolation2/Makefile
+++ b/src/test/isolation2/Makefile
@@ -22,6 +22,9 @@ all: test_python pg_isolation2_regress$(X) all-lib data extended_protocol_test s
 extended_protocol_test: extended_protocol_test.c
 	$(CC) $(CPPFLAGS) -I$(top_builddir)/src/interfaces/libpq -L$(GPHOME)/lib -L$(top_builddir)/src/interfaces/libpq  -o $@ $< -lpq
 
+test_parallel_retrieve_cursor_extended_query: test_parallel_retrieve_cursor_extended_query.c
+	$(CC) $(CPPFLAGS) -I$(top_builddir)/src/interfaces/libpq -L$(GPHOME)/lib -L$(top_builddir)/src/interfaces/libpq  -o $@ $< -lpq
+
 test_python:
 	python helpers_test.py
 
@@ -63,11 +66,56 @@ clean distclean:
 
 install: all gpdiff.pl gpstringsubs.pl
 
-installcheck: install
+installcheck: install installcheck-parallel-retrieve-cursor
 	./pg_isolation2_regress $(EXTRA_REGRESS_OPTS) --init-file=$(top_builddir)/src/test/regress/init_file --init-file=./init_file_isolation2 --bindir='$(bindir)' --inputdir=$(srcdir) --load-extension=gp_inject_fault --schedule=$(srcdir)/isolation2_schedule
 
 installcheck-resgroup: install
 	./pg_isolation2_regress $(EXTRA_REGRESS_OPTS) --init-file=$(top_builddir)/src/test/regress/init_file --init-file=./init_file_resgroup --bindir='$(bindir)' --inputdir=$(srcdir) --dbname=isolation2resgrouptest --load-extension=gp_inject_fault --schedule=$(srcdir)/isolation2_resgroup_schedule
 
-installcheck-parallel-cursor: install
-	./pg_isolation2_regress $(EXTRA_REGRESS_OPTS) --init-file=$(top_builddir)/src/test/regress/init_file --init-file=./init_file_parallel_cursor --bindir='$(bindir)' --inputdir=$(srcdir) --dbname=isolation2parallelcursor --schedule=$(srcdir)/parallel_cursor_schedule
+# PARALLEL RETRIEVE CURSOR related tests require 3 running segment. Some issues have been seen on CI that
+# one segment is not running during the test. Add check here to make it fails earlier.
+installcheck-parallel-retrieve-cursor-check-segments:
+	gp_state=$$(gpstate) && \
+	seg_count=$$(echo "$${gp_state}" | grep "Total primary segment valid (at master)" | awk '{print $$NF}') ; \
+	if [ -z "$${seg_count}" ] || [ "$${seg_count}" != 3 ] ; then \
+		echo "The tests require 3 valid segments." ; \
+		echo "gpstate is: \n $${gp_state}" ; \
+		echo "seg_count is: \n $${seg_count}" ; \
+		exit -1 ; \
+	fi
+
+installcheck-parallel-retrieve-cursor: install installcheck-parallel-retrieve-cursor-check-segments test_parallel_retrieve_cursor_extended_query
+	# Before running test, set statement_timeout to 1 minute so that even if some
+	# error make 'gp_wait_parallel_retrieve_cursor()' hang, it will be canceled when timeout.
+	#
+	# And also add test for test_parallel_retrieve_cursor_extended_query, only need to check command rc==0
+	default_master_timeout=$$(gpconfig -s statement_timeout | grep "Master" | cut -d':' -f2) && \
+	default_segment_timeout=$$(gpconfig -s statement_timeout | grep "Segment" | cut -d':' -f2) && \
+	if [ -z "$${default_master_timeout}" ] || [ -z "$${default_segment_timeout}" ] ; then \
+	  echo " --- default_master_timeout is: $${default_master_timeout} ---"; \
+	  echo " --- default_segment_timeout is: $${default_segment_timeout} ---"; \
+	  echo " Get gpconfig returns empty result " && exit -1; \
+	fi; \
+	gpconfig -c statement_timeout -v 60000 && \
+	gpstop -u && \
+	gpconfig -s statement_timeout && \
+	if [[ "$$OSTYPE" == "darwin"* ]] && gpconfig -s gp_interconnect_type | grep udp -q ; then \
+		echo  "**NOTE** Ignore parallel retrieve cursor fault injection test because of a known MacOS issue https://github.com/greenplum-db/gpdb/issues/8374" ; \
+		./pg_isolation2_regress $(EXTRA_REGRESS_OPTS) --init-file=$(top_builddir)/src/test/regress/init_file --init-file=./init_file_parallel_retrieve_cursor --bindir='$(bindir)' --inputdir=$(srcdir) --dbname=isolation2parallelretrcursor --load-extension=gp_inject_fault --schedule=$(srcdir)/parallel_retrieve_cursor_schedule --exclude-test="parallel_retrieve_cursor/fault_inject_2" ; \
+		ret1=$$? ; \
+	else \
+		./pg_isolation2_regress $(EXTRA_REGRESS_OPTS) --init-file=$(top_builddir)/src/test/regress/init_file --init-file=./init_file_parallel_retrieve_cursor --bindir='$(bindir)' --inputdir=$(srcdir) --dbname=isolation2parallelretrcursor --load-extension=gp_inject_fault --schedule=$(srcdir)/parallel_retrieve_cursor_schedule ; \
+		ret1=$$? ; \
+	fi; \
+	./test_parallel_retrieve_cursor_extended_query "gpadmin" "postgres" > test_parallel_retrieve_cursor_extended_query.log 2>&1 ; \
+	ret2=$$? ; \
+	if [ "$${ret2}" == 0 ]; then \
+		echo "[PASS]: test_parallel_retrieve_cursor_extended_query test pass. See test_parallel_retrieve_cursor_extended_query.log." ; echo "" ; \
+	else \
+		echo "[ERROR]: test_parallel_retrieve_cursor_extended_query test failed." ; \
+		cat test_parallel_retrieve_cursor_extended_query.log ; echo "" ; \
+	fi; \
+	gpconfig -c statement_timeout -v $${default_segment_timeout} -m $${default_master_timeout} && \
+	gpstop -u && \
+	gpconfig -s statement_timeout && \
+	exit "$$(( $${ret1} || $${ret2} ))"
